### ISSUE TITLE
customising social media links in people/project cards

### ISSUE THREAD

**Issue by AlexJohne** [weecology/website#22]
Hi,

I'm new to making websites, blogdown and the academic theme, and am at a loss when it comes to removing the social media buttons or adding personal links to the social media buttons in the project/people cards in your version of the academic theme website template. I also could not find any documentation on that issue. Could you please help me out? 

Thanks so much

**Comment by ethanwhite** [comment]
Hi @AlexJohne - we're running a really old version of the hugo academic theme on our site so I think you're better off asking in the repo for the theme: https://github.com/gcushen/hugo-academic where they can give you up to date info. (also, I don't think I've done that here because at the time I tried at least it was difficult).
